-- MySQL Script generated by MySQL Workbench
-- Wed Dec 17 08:17:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema camodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `camodb` ;

-- -----------------------------------------------------
-- Schema camodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camodb` DEFAULT CHARACTER SET utf8mb4 ;
USE `camodb` ;

-- -----------------------------------------------------
-- Table `camodb`.`NPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`NPC` (
  `idNPC` INT NOT NULL AUTO_INCREMENT,
  `nameFirst` VARCHAR(45) NOT NULL,
  `nameLast` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NOT NULL,
  `gender` ENUM('male', 'female', 'non-binary') NOT NULL,
  PRIMARY KEY (`idNPC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`storylet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`storylet` (
  `idStorylet` INT NOT NULL AUTO_INCREMENT,
  `idNPC` INT NOT NULL,
  `nameStorylet` VARCHAR(45) NOT NULL,
  `contentStorylet` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idStorylet`),
  UNIQUE INDEX `uniq_npc_storylet` (`idNPC` ASC, `nameStorylet` ASC) VISIBLE,
  INDEX `idNPC` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_storylet_npc`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `nameFirst` VARCHAR(45) NULL DEFAULT NULL,
  `nameLast` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`completedStorylet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`completedStorylet` (
  `idStorylet` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idStorylet`, `idUser`),
  INDEX `fk_completed_storylet_user` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_completed_storylet_storylet`
    FOREIGN KEY (`idStorylet`)
    REFERENCES `camodb`.`storylet` (`idStorylet`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_completed_storylet_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`tasks` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `taskName` VARCHAR(45) NOT NULL,
  `taskDetails` TEXT NOT NULL,
  `idNPC` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_tasks_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `camodb`.`user_task`
-- -----------------------------------------------------
CREATE TABLE user_task (
  idUser INT NOT NULL,
  idTask INT NOT NULL,
  status ENUM('active','completed','failed') NOT NULL DEFAULT 'active',
  startedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt DATETIME NULL,
  PRIMARY KEY (idUser, idTask),
  CONSTRAINT fk_user_task_user
    FOREIGN KEY (idUser) REFERENCES user(idUser)
    ON DELETE CASCADE,
  CONSTRAINT fk_user_task_task
    FOREIGN KEY (idTask) REFERENCES tasks(idTask)
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Table `camodb`.`relationshipType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`relationshipType` (
  `idRelationshipType` INT NOT NULL AUTO_INCREMENT,
  `typeRelationship` ENUM('friend', 'stranger', 'enemy', 'acquaintance', 'mentor', 'student','family') NOT NULL,
  `descriptionRelationship` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idRelationshipType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`playerNPCrelationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`playerNPCrelationship` (
  `idUser` INT NOT NULL,
  `idNPC` INT NOT NULL,
  `idRelationshipType` INT NOT NULL,
  `relTypeIntensity` FLOAT NOT NULL,
  `trust` FLOAT NULL,
  PRIMARY KEY (`idUser`, `idNPC`),
  INDEX `idNPC` (`idNPC` ASC) VISIBLE,
  INDEX `idRelationshipType` (`idRelationshipType` ASC) VISIBLE,
  CONSTRAINT `fk_rel_npc`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_rel_type`
    FOREIGN KEY (`idRelationshipType`)
    REFERENCES `camodb`.`relationshipType` (`idRelationshipType`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_rel_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`precondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`precondition` (
  `idPrecondition` INT NOT NULL AUTO_INCREMENT,
  `idNPC` INT NOT NULL,
  `nameCondition` VARCHAR(64) NOT NULL,
  `conditionDescription` TEXT NOT NULL,
  PRIMARY KEY (`idPrecondition`),
  INDEX `fk_precondition_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_precondition_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`choice` (
  `idChoice` INT NOT NULL AUTO_INCREMENT,
  `idSourceStorylet` INT NOT NULL,
  `choiceText` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idChoice`),
  INDEX `fk_choice_storylet1_idx` (`idSourceStorylet` ASC) VISIBLE,
  CONSTRAINT `fk_choice_storylet1`
    FOREIGN KEY (`idSourceStorylet`)
    REFERENCES `camodb`.`storylet` (`idStorylet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NULL DEFAULT NULL,
  `itemType` VARCHAR(45) NULL DEFAULT NULL,
  `itemDescription` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`userItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`userItem` (
  `idUser` INT NOT NULL,
  `iditem` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_userItem_user1_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`iditem`, `idUser`),
  CONSTRAINT `fk_userItem_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userItem_item1`
    FOREIGN KEY (`iditem`)
    REFERENCES `camodb`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`NPCItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`NPCItem` (
  `iditem` INT NOT NULL,
  `idNPC` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`iditem`, `idNPC`),
  INDEX `fk_NPCItem_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_NPCItem_item1`
    FOREIGN KEY (`iditem`)
    REFERENCES `camodb`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NPCItem_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npc_user_memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npc_user_memory` (
  `idNPC` INT NOT NULL,
  `idUser` INT NOT NULL,
  `kbText` LONGTEXT NULL DEFAULT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idNPC`, `idUser`),
  INDEX `fk_KB_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_KB_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KB_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`background`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`background` (
  `idNPC` INT NOT NULL,
  `BGcontent` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idNPC`),
  INDEX `fk_background_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_background_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`storylet_preconditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`storylet_preconditions` (
  `idPrecondition` INT NOT NULL,
  `idStorylet` INT NOT NULL,
  PRIMARY KEY (`idPrecondition`, `idStorylet`),
  INDEX `fk_preconditions_storylet1_idx` (`idStorylet` ASC) VISIBLE,
  CONSTRAINT `fk_preconditions_precondition1`
    FOREIGN KEY (`idPrecondition`)
    REFERENCES `camodb`.`precondition` (`idPrecondition`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconditions_storylet1`
    FOREIGN KEY (`idStorylet`)
    REFERENCES `camodb`.`storylet` (`idStorylet`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`emotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`emotion` (
  `idEmotion` INT NOT NULL AUTO_INCREMENT,
  `emotion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmotion`),
  UNIQUE INDEX `emotion_UNIQUE` (`emotion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`userEmotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`userEmotion` (
  `idUser` INT NOT NULL,
  `idEmotion` INT NOT NULL,
  `emotionIntensity` FLOAT NOT NULL,
  INDEX `fk_userEmotion_user1_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`idEmotion`, `idUser`),
  CONSTRAINT `fk_userEmotion_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userEmotion_emotion1`
    FOREIGN KEY (`idEmotion`)
    REFERENCES `camodb`.`emotion` (`idEmotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npcEmotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npcEmotion` (
  `idNPC` INT NOT NULL,
  `idEmotion` INT NOT NULL,
  `emotionIntensity` FLOAT NOT NULL,
  PRIMARY KEY (`idNPC`, `idEmotion`),
  INDEX `fk_npcEmotion_emotion1_idx` (`idEmotion` ASC) VISIBLE,
  CONSTRAINT `fk_npcEmotion_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_npcEmotion_emotion1`
    FOREIGN KEY (`idEmotion`)
    REFERENCES `camodb`.`emotion` (`idEmotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npcNPCrelationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npcNPCrelationship` (
  `idNPC_1` INT NOT NULL,
  `idNPC_2` INT NOT NULL,
  `idRelationshipType` INT NOT NULL,
  `relTypeIntensity` FLOAT NOT NULL,
  `trust` FLOAT NOT NULL,
  PRIMARY KEY (`idNPC_1`, `idNPC_2`),
  INDEX `fk_npcNPCrelationship_NPC1_idx` (`idNPC_1` ASC) VISIBLE,
  INDEX `fk_npcNPCrelationship_NPC2_idx` (`idNPC_2` ASC) VISIBLE,
  CONSTRAINT `fk_npcNPCrelationship_relationshipType1`
    FOREIGN KEY (`idRelationshipType`)
    REFERENCES `camodb`.`relationshipType` (`idRelationshipType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_npcNPCrelationship_NPC1`
    FOREIGN KEY (`idNPC_1`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_npcNPCrelationship_NPC2`
    FOREIGN KEY (`idNPC_2`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npc_npc_memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npc_npc_memory` (
  `idNPC_1` INT NOT NULL,
  `idNPC_2` INT NOT NULL,
  `kbText` LONGTEXT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`idNPC_1`, `idNPC_2`),
  INDEX `fk_npc_npc_memory_NPC2_idx` (`idNPC_2` ASC) VISIBLE,
  CONSTRAINT `fk_npc_npc_memory_NPC1`
    FOREIGN KEY (`idNPC_1`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_npc_npc_memory_NPC2`
    FOREIGN KEY (`idNPC_2`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`user_precondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`user_precondition` (
  `idUser` INT NOT NULL,
  `idPrecondition` INT NOT NULL,
  `conditionMet` TINYINT(1) NOT NULL DEFAULT 0,
  `updatedAt` DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`, `idPrecondition`),
  INDEX `fk_user_precondition_precondition1_idx` (`idPrecondition` ASC) VISIBLE,
  CONSTRAINT `fk_user_precondition_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_precondition_precondition1`
    FOREIGN KEY (`idPrecondition`)
    REFERENCES `camodb`.`precondition` (`idPrecondition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `camodb`.`npc_persona`
-- -----------------------------------------------------
CREATE TABLE npc_persona (
  idNPC INT NOT NULL,
  role VARCHAR(64) NOT NULL,
  personality_traits TEXT NOT NULL,
  emotional_tendencies TEXT NOT NULL,
  emotion_decay_rate FLOAT DEFAULT 0.9,
  emotion_reactivity FLOAT DEFAULT 1.0,
  speech_style TEXT NULL,
  moral_alignment TEXT NULL,
  PRIMARY KEY (idNPC),
  CONSTRAINT fk_npc_persona_npc
    FOREIGN KEY (idNPC)
    REFERENCES NPC(idNPC)
    ON DELETE CASCADE
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `camodb`.`emotion_guess_game`
-- -----------------------------------------------------
CREATE TABLE camodb.emotion_guess_game (
  idUser INT NOT NULL,
  idNPC INT NOT NULL,
  idEmotion INT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 0,

  -- game state
  described TINYINT(1) NOT NULL DEFAULT 0,
  guessed_correctly TINYINT(1) NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,

  -- narrative / pedagogy
  learning_objective VARCHAR(128) NULL,
  description_text MEDIUMTEXT NULL,
  difficulty_level ENUM('easy','medium','hard') NOT NULL DEFAULT 'easy',
  hint_level INT NOT NULL DEFAULT 0,

  -- timing
  startedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt DATETIME NULL,

  PRIMARY KEY (idUser, idNPC, idEmotion),

  INDEX idx_egg_user_npc_state (idUser, idNPC, guessed_correctly, described),

  CONSTRAINT fk_egg_user
    FOREIGN KEY (idUser) REFERENCES user(idUser)
    ON DELETE CASCADE,

  CONSTRAINT fk_egg_npc
    FOREIGN KEY (idNPC) REFERENCES NPC(idNPC)
    ON DELETE CASCADE,

  CONSTRAINT fk_egg_emotion
    FOREIGN KEY (idEmotion) REFERENCES emotion(idEmotion)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`emotion_guess_attempt`
-- -----------------------------------------------------
CREATE TABLE camodb.emotion_guess_attempt (
  idAttempt INT NOT NULL AUTO_INCREMENT,
  idUser INT NOT NULL,
  idNPC INT NOT NULL,
  idEmotion INT NOT NULL,

  player_guess VARCHAR(64) NOT NULL,
  correct TINYINT(1) NOT NULL,

  feedback_text TEXT NULL,
  attemptedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (idAttempt),

  INDEX idx_guess_lookup (idUser, idNPC, idEmotion),

  CONSTRAINT fk_ega_parent
    FOREIGN KEY (idUser, idNPC, idEmotion)
    REFERENCES emotion_guess_game(idUser, idNPC, idEmotion)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- -----------------------------------------------------
-- Seed data
-- -----------------------------------------------------

-- emotions
INSERT INTO emotion (emotion)
VALUES
  ('happy'),
  ('sad'),
  ('angry'),
  ('afraid'),
  ('surprised'),
  ('disgusted'),
  ('calm'),
  ('excited');


-- Relationship types
INSERT INTO relationshipType
(idRelationshipType, typeRelationship, descriptionRelationship)
VALUES
(1, 'friend',  'Friendly / positive relationship'),
(2, 'stranger', 'person unkown'),
(3, 'enemy', 'hostile feelings'),
(4, 'acquaintance',  'someone just met or only met a few times'),
(5, 'mentor',  'teacher role'),
(6, 'family',  'related to the player/npc'),
(7, 'student', 'Learner or pupil in a guided or teaching relationship');

-- initial users

INSERT INTO user
(userName, nameFirst, nameLast)
VALUES
('Gabe', 'Gabriel', 'Malone'),
('Lisa', 'Lisa', 'Gilmore'),
('Soheil', 'Soheil', 'Saneei');

-- initial NPCs
INSERT INTO NPC
(nameFirst, nameLast, age, gender)
VALUES
('Emory',  NULL, 26, 'female');

INSERT INTO npc_persona (
  idNPC,
  role,
  personality_traits,
  emotional_tendencies,
  emotion_decay_rate,
  emotion_reactivity,
  speech_style,
  moral_alignment
) VALUES (
  1,
  'therapist-mentor',

  'Warm, patient, emotionally attuned, gently playful, supportive, non-judgmental',

  'Defaults to calm and curiosity; validates uncertainty; responds to mistakes with reassurance; gradually scaffolds emotional insight',

  0.9,
  0.8,

  'Speaks in natural, spoken sentences with a warm, steady rhythm. 
  Uses simple language without sounding instructional. 
  Prefers everyday phrasing over metaphors. 
  When she does use metaphors, they come from ordinary life and feel personal, not illustrative. 
  Often blends observation and feeling into a single sentence. 
  Avoids overexplaining, avoids stacked descriptions, and sounds like someone talking, not teaching.',

  'care-based, relational'
);

INSERT INTO background (idNPC, BGcontent)
VALUES (
  1,
  'Emory believes that emotions are easier to understand when they are explored through play, imagination, and gentle curiosity. She often uses games, and collaborative guessing to help her patients notice body sensations, thoughts, and situations connected to feelings.'
);

INSERT INTO playerNPCrelationship (
  idUser,
  idNPC,
  idRelationshipType,
  relTypeIntensity,
  trust
)
VALUES (
  1,
  1,
  (SELECT idRelationshipType FROM relationshipType WHERE typeRelationship = 'student'),
  0.5,
  50
);